export default function languageDetector() {
  const languageDetector = {
    English:{
      one: '1',
      two: '2',
      three: '3',
      tree: '3',
      four: '4',
      five: '5',
      six: '6',
      seven: '7',
      eight: '8',
      nine: '9',
      zero: '0',
      plus: '+',
      minus: '-',
      times: '*',
      divide: '/',
      open: '(',
      close: ')',
      pie: '𝜋',
      comma: ',',
      exponent: '^',
      'greater than': '>',
      'less than': '<',
      'greater or equal': '>=',
      'less or equal': '<=',
      permutation: '!',
      combination: 'C',
      delete: '--',
      clear: '<-',
      return: '->',
    },
    Bisaya: {
      uno: '1',
      dos: '2',
      tres: '3',
      dress: '3',
      trees: '3',
      kwatro: '4',
      quatro: '4',
      singko: '5',
      sais: '6',
      size: '6',
      syete: '7',
      city: '7',
      otso: '8',
      "what's up": '8',
      utsu: '8',
      nuybi: '9',
      navy: '9',
      maybe: '9',
      noybe: '9',
      zero: '0',
      siro: '0',
      dungaga: '+',
      dunga: '+',
      dumaga: '+',
      dong: '+',
      dongga: '+',
      dung: '+',
      umaga: '+',
      bawasi: '-',
      padaghani: '*',
      padagan: '*',
      panag: '*',
      panagan: '*',
      padagdag: '*',
      panagini: '*',
      tungaa: '/',
      tunga: '/',
      bayani: '/',
      mainit: '/',
      'oo nga': '/',
      abria: '(',
      abri: '(',
      sirado: ')',
      pie: '𝜋',
      human: ',',
      isaka: '^',
      'mas dako': '>',
      'maz dako': '>',
      masdako: '>',
      'mas gamay': '<',
      gamay: '<',
      'dako o pareha': '>=',
      'gamay o pareha': '<=',
      permutasyon: '!',
      permutation: '!',
      combayni: 'C',
      combining: 'C',

      tangali: '--',
      tangalin: '--',
      tanghali: '--',
      'ang galing': '--',
      erisa: '<-',
      erissa: '<-',
      elisa: '<-',
      irisa: '<-',
      lisa: '<-',
      'it is a': '<-',
      'undangi na': '->',
      'undang ina': '->',
      'undang in': '->',
      tangina: '->',
      undang: '->',
      'unang ina': '->',
      'ang dami na': '->',
    },
    Tagalog:{
      isa:'1',
      dalawa:'2',
      tatlo:'3',
      apat:'4',
      lima:'5',
      anim:'6',
      pito:'7',
      walo:'8',
      siyam:'9',
      siam:'9',
      wala:'0',
      dagdagan:'+',
      bawasan:'-',
      paramihin:'*',
      hatiin:'/',
      buksan:'(',
      sarado:')',
      pie: '𝜋',
      kama:',',
      itaas:'^',
      'mas malaki':'>',
      'maliit':'<',
      'mas maliit':'<',
      'malaki o pareha':'>=',
      'maliit o pareha':'<=',
      permutasyon:'!',
      kombinasyon:'C',
      tanggalin: '--',
      burahin:'<-',
      buray:'<-',
      'okay na yan':'->',
      okay:'->',
      'okay na' :'->'
      
    }
  };
  return languageDetector;
}
