export default function languageDetector() {
  const languageDetector = {
    English:{
      one: '1',
      two: '2',
      three: '3',
      tree: '3',
      four: '4',
      five: '5',
      six: '6',
      seven: '7',
      eight: '8',
      nine: '9',
      zero: '0',
      plus: '+',
      minus: '-',
      times: '*',
      divide: '/',
      open: '(',
      close: ')',
      pie: '𝜋',
      comma: ',',
      exponent: '^',
      'greater than': '>',
      'less than': '<',
      'greater or equal': '>=',
      'less or equal': '<=',
      permutation: '!',
      combination: 'C',
      delete: '--',
      clear: '<-',
      return: '->',
    },
    Bisaya: {
      isa: '1',
      duha: '2',
      dua: '2',
      tulo: '3',
      tula: '3',
      upat:'4',
      opat: '4',
      quatro: '4',
      lima: '5',
      unom: '6',
      onom: '6', 
      unum:'6',
      unong:'6',
      size: '6',
      pito: '7',
      ito: '7',
      tito: '7',
      walo: '8',
      "what's up": '8',
      utsu: '8',
      siam: '9',
      ciam: '9',
      siyam:'9',
      nueva: '9',
      maybe: '9',
      noybe: '9',
      zero: '0',
      siro: '0',
      dungaga: '+',
      dunga: '+',
      dumaga: '+',
      dong: '+',
      dongga: '+',
      dung: '+',
      umaga: '+',
      bawasi: '-',
      padaghani: '*',
      padagan: '*',
      panag: '*',
      panagan: '*',
      padagdag: '*',
      panagini: '*',
      tungaa: '/',
      tunga: '/',
      bayani: '/',
      mainit: '/',
      'oo nga': '/',
      abria: '(',
      abri: '(',
      sirado: ')',
      pie: '𝜋',
      human: ',',
      isaka: '^',
      'mas dako': '>',
      'maz dako': '>',
      'mazda ko': '>',
      masdako: '>',
      'mas gamay': '<',
      gamay: '<',
      'dako o pareha': '>=',
      'gamay o pareha': '<=',
      permutasyon: '!',
      permutation: '!',
      combayni: 'C',
      combining: 'C',
      tanggalin: '--',
      tanggal: '--',
      tangal: '--',
      tangali: '--',
      tangalin: '--',
      tanghali: '--',
      'ang gali': '--',
      'ang galing': '--',
      erisa: '<-',
      erissa: '<-',
      elisa: '<-',
      irisa: '<-',
      lisa: '<-',
      'it is a': '<-',
      'undangi na': '->',
      'undang ina': '->',
      'undang in': '->',
      tangina: '->',
      undang: '->',
      'unang ina': '->',
      'ang dami na': '->',
      'sir bart': '||',
      'server': '||',
      'kana': '|'
    },
    Tagalog:{
      isa:'1',
      dalawa:'2',
      tatlo:'3',
      apat:'4',
      lima:'5',
      anim:'6',
      pito:'7',
      walo:'8',
      siyam:'9',
      siam:'9',
      wala:'0',
      dagdagan:'+',
      bawasan:'-',
      paramihin:'*',
      hatiin:'/',
      buksan:'(',
      sarado:')',
      pie: '𝜋',
      kama:',',
      itaas:'^',
      'mas malaki':'>',
      'maliit':'<',
      'mas maliit':'<',
      'malaki o pareha':'>=',
      'maliit o pareha':'<=',
      permutasyon:'!',
      kombinasyon:'C',
      tanggalin: '--',
      burahin:'<-',
      buray:'<-',
      'okay na yan':'->',
      okay:'->',
      'okay na' :'->'
      
    },
    Japanese:{
      itzy:'1',
      it:'1',
      itchy:'1',
      knee:'2',
      son:'3',
      sun:'3',
      yun:'4',
      go:'5',
      roku:'6',
      nana:'7',
      hachi:'8',
      q:'9',
      zero:'0',
      puras:'+',
      pura:'+',
      minus:'-',
      kai:'*',
      walker:'/',
      akiro:'(',
      akeru:'(',
      chikai:')',
      chikay:')',
      pie: '𝜋',
      kuma:',',
      kun:',',
      'shih tzu':'^',
      shis:'^',
      'yuri uki':'>',
      yuri:'>',
      'miman':'<',
      'meman':'<',
      'malaki o pareha':'>=',
      'maliit o pareha':'<=',
      permutasyon:'!',
      kombinasyon:'C',
      tanggalin: '--',
      burahin:'<-',
      buray:'<-',
      'okay na yan':'->',
      okay:'->',
      'okay na' :'->'
      
    }
    
  };
  return languageDetector;
}
